### ISSUE TITLE
 [MAC-Chrome-850-게시글 목록] 로그인하지 않은 상태에서의 접근 가능

### ISSUE THREAD

**Issue by gelong25** [100-hours-a-week/2-hyun-lee-community-issue#3]
**버그 설명**
로그인하지 않은 상태에서 게시글 목록 페이지에 접근할 수 있는 문제가 발생합니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 브라우저에서 로그아웃 상태를 확인합니다.
2. http://52.78.32.212/board 페이지로 이동합니다.
3. 로그인 없이 게시글 목록이 표시되는 것을 확인합니다.

**예상한 동작**
로그인하지 않은 사용자가 게시글 목록에 접근하려고 하면 "로그인이 필요합니다" 라는 메시지가 출력되며 로그인 페이지로 리다이렉션 됩니다. 

**스크린샷**
![image](https://github.com/user-attachments/assets/1727434c-f631-43ac-824e-343e471ba876)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [chrome]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**Comment by donet12** [comment]
수정완료...
