### ISSUE TITLE
 [MAC-크롬-회원정보수정페이지] 닉네임수정 버튼으로 2번의 요청이가능함 

### ISSUE THREAD

**Issue by yosep98** [100-hours-a-week/2-hyun-lee-community-issue#4]
**버그 설명**
닉네임 수정 버튼 클릭 후 토스트 메세지가 끝나기 전에 다른 닉네임으로 수정할 경우 프로필 이미지가 깨지고 최종 수정한 닉네임으로 변경됨

**재현하는 방법**
동작을 재현하는 단계:
1. 회원정보 페이지 이동
2. 회원정보의 닉네임 수정 ex손흥민123
3. 수정 버튼 클릭 후 토스트 메세지가 끝나기 전에 다른 이름으로 수정 ex)손흥민

**예상한 동작**
변경이 되지 않기를 예상함

**스크린샷**
 

https://github.com/user-attachments/assets/77017de0-2788-4f38-8a4f-7ae3884ad253

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [chrome]
 - Version [22]

**Comment by donet12** [comment]
수정완료..
