### ISSUE TITLE
 [Windows-Chrome-1920-게시글 목록 조회] 게시글 상세보기 클릭 

### ISSUE THREAD

**Issue by JiwonHwang01** [100-hours-a-week/2-hyun-lee-community-issue#5]
**버그 설명**
게시글 상세 조회 기능이 post-item 전체에 적용되면 어떨까하는 생각입니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 목록 조회로 이동
2. post-header가 아닌 다른 부분을 클릭
3. 이벤트 리스너가 동작하지 않음

**예상한 동작**
클릭 이벤트 리스너가 post-item 전제에 적용되어 있으면 좋을 거 같음

**스크린샷**
![image](https://github.com/user-attachments/assets/fcaec560-5998-435c-bc18-3caec1cc0dce)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: Windows 11
 - Browser [Chorme]

**Comment by donet12** [comment]
수정 완료..
